package Interfaz.GestionCliente;

import javax.swing.JFrame;
import Negocio.GestorCliente;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Event;

/**
 *
 * @author juan
 */
public class IngresoDeCliente extends javax.swing.JFrame {

    /**
     * Creates new form IngresoDeCliente     */
    public IngresoDeCliente(String num) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Clio - Guardar cliente en BD");
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/clioLogo.png")).getImage() );
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jTextFieldNumero.setText(num);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /*La siguiente función convierte la primera letra en mayúscula de cada cadena String*/
    public String primeraLetraMayus(String str) {
        if (str == null || str.isEmpty()) {
            return str;            
        } else {
            return str.substring(0, 1).toUpperCase() + str.substring(1); 
        }
    }
    
    /*La siguiente función hace uso de la función "primeraLetraMayus" ateriormente definida. 
    La presente función toma una cadena String y convierte la primera letra de cada cadena a 
    mayúscula. Esto se usa posteriormente para hacer la conversión de los campos del nombre o
    apellido.*/
    public String convertirCadenaMayus(String cadena){
        String cadenaSalida = "";
        String[] palabras = cadena.split(" ");
        for (String palabra : palabras){
            cadenaSalida = cadenaSalida + primeraLetraMayus(palabra)+ " " ;
        }
        return cadenaSalida;
    }
    
    /*Es necesario blindar el programa de posibles fallos, por eso la siguiente función se usa para
    asegurarnos de que los 3 campos jTextField de la dirección del cliente tienen algún valor, en caso
    de que no, lo notificará al usuario por medio del uso de páneles.*/
    public boolean avisarFaltaCamposDir(){
        boolean camposLlenos = true;
        String campodir1 = jTextFieldDireccion1.getText();
        String campodir2 = jTextFieldDireccion2.getText();
        String campodir3 = jTextFieldDireccion3.getText();
        if ( campodir1.length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo 1 de dirección está vacío", "Dirección incompleta", JOptionPane.WARNING_MESSAGE);
            camposLlenos = false;
        }
        if ( campodir2.length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo 2 de dirección está vacío", "Dirección incompleta", JOptionPane.WARNING_MESSAGE);
            camposLlenos = false;
        }
        if ( campodir3.length() == 0) {
            JOptionPane.showMessageDialog(null, "El campo 3 de dirección está vacío", "Dirección incompleta", JOptionPane.WARNING_MESSAGE);
            camposLlenos = false;
        }
        return camposLlenos;
    }
    
    public void guardarCliente(String numero){
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea ingresar cliente a la base de datos?", "Guardar cliente", JOptionPane.OK_CANCEL_OPTION);
        /*Si el número tomado del jTextFieldNumero no es de 10 digitos, no permitirá guardar los datos
        y lo notificará por medio de un panel.*/
        if( numero.length() == 10){
            if(opcion == 0){
                Negocio.GestorCliente gestor = new Negocio.GestorCliente();
                String nombre = convertirCadenaMayus( jTextFieldNombre.getText() );
                String apellido = convertirCadenaMayus( jTextFieldApellido.getText() );
                String direccion = "";
                String piso = "";
                /*Dentro del programa hay dos formas de guardar la dirección del cliente, por medio
                de los jTextField dispuestos para facilitar la tarea de ingresar dicha dirección, o 
                por medio del botón. La opción del botón existe debido a que pueden haber dirección
                que no empiecen con cll o cra sino con tv o dg, es decir, otro tipo de formato de dirección.
                El programa le dará prioridad a la dirección tomada por el botón, si el usuario lo hizo por
                medio del botón, entonces tomará dicha dirección.*/
                if ( this.otraDir.length() != 0 ) {
                    direccion = this.otraDir;
                    if ( jTextFieldPiso.getText().equals("") ) {
                        piso = "-";
                    }else{
                        piso = jTextFieldPiso.getText();
                    }                      
                    String mensajeSalida = gestor.ingresarDatos(nombre, apellido, direccion, piso, numero);
                    jTextAreaLog.setText(mensajeSalida);
                }else{
                    if ( avisarFaltaCamposDir() ) {
                        if( jRadioCll.isSelected() ){
                            direccion = "Cll "+jTextFieldDireccion1.getText()+" # "+jTextFieldDireccion2.getText()+
                                    " - "+jTextFieldDireccion3.getText();
                        }else if( jRadioCra.isSelected() ){
                            direccion = "Cra "+jTextFieldDireccion1.getText()+" # "+jTextFieldDireccion2.getText()+
                                    " - "+jTextFieldDireccion3.getText();
                        }
                        if ( jTextFieldPiso.getText().equals("") ) {
                            piso = "-";
                        }else{
                            piso = jTextFieldPiso.getText();
                        }  
                        String mensajeSalida = gestor.ingresarDatos(nombre, apellido, direccion, piso, numero);
                        jTextAreaLog.setText(mensajeSalida);
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "El número no es de 10 digitos", "Revise número", JOptionPane.ERROR_MESSAGE);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPiso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonImprimir = new javax.swing.JButton();
        jRadioCll = new javax.swing.JRadioButton();
        jRadioCra = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDireccion2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDireccion3 = new javax.swing.JTextField();
        jButtonOtraDir = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jLabel1.setText("Nombre(s)");

        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyReleased(evt);
            }
        });

        jLabel2.setText("Apellido(s)");

        jTextFieldDireccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDireccion1KeyReleased(evt);
            }
        });

        jLabel3.setText("Dirección");

        jTextFieldPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPisoKeyReleased(evt);
            }
        });

        jLabel4.setText("Piso");

        jLabel5.setText("Número");

        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyReleased(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Regresar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ingrese los datos que se piden a continuación y luego");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("dé clic en Guardar para ingresar cliente a la base de ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Datos.");

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioCll);
        jRadioCll.setText("Cll");

        buttonGroup1.add(jRadioCra);
        jRadioCra.setText("Cra");

        jLabel10.setText("#");

        jTextFieldDireccion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDireccion2KeyReleased(evt);
            }
        });

        jLabel11.setText("-");

        jTextFieldDireccion3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDireccion3KeyReleased(evt);
            }
        });

        jButtonOtraDir.setText("Otra dirección");
        jButtonOtraDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtraDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jButtonGuardar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldApellido)
                                            .addComponent(jTextFieldNombre)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldPiso, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jRadioCll)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jRadioCra)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButtonCancelar)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTextFieldDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldDireccion3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jButtonOtraDir)))))))))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButtonImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioCll)
                    .addComponent(jRadioCra)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDireccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonOtraDir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImprimir)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Realmente desea cancelar el ingreso?\nLos datos se perderán", "Advertencia", JOptionPane.WARNING_MESSAGE);
        if(opcion == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        Negocio.GestorCliente gestor = new Negocio.GestorCliente();
        gestor.imprimirDomicilio(jTextFieldNombre.getText(), jTextFieldApellido.getText(),
                jTextFieldDireccion1.getText(), jTextFieldPiso.getText(), jTextFieldNumero.getText());
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        String numero = jTextFieldNumero.getText();
        guardarCliente(numero);
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldNumeroKeyReleased

    private void jTextFieldDireccion1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccion1KeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldDireccion1KeyReleased

    private void jTextFieldApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldApellidoKeyReleased

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jButtonOtraDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtraDirActionPerformed
         this.otraDir = JOptionPane.showInputDialog(null, "Ingrese la dirección del cliente a continuación","Ingrese la dirección", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonOtraDirActionPerformed

    private void jTextFieldPisoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPisoKeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldPisoKeyReleased

    private void jTextFieldDireccion2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccion2KeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldDireccion2KeyReleased

    private void jTextFieldDireccion3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccion3KeyReleased
        if ( evt.getKeyCode() == evt.VK_ENTER ) {
            String numero = jTextFieldNumero.getText();
            guardarCliente(numero);
        }
    }//GEN-LAST:event_jTextFieldDireccion3KeyReleased

    /*Dentro del programa hay una opción para guardar la dirección de un cliente por medio de un
    botón en caso de que la dirección sea de otro tipo como tv(tranversal), ya que los radio button
    sólo contemplan las opciones cll o cra (calle o carrera).
    La variable "otraDir" se creó para especificar que se guarda la dirección por medio del botón*/
    private String otraDir = "";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonOtraDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioCll;
    private javax.swing.JRadioButton jRadioCra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldDireccion2;
    private javax.swing.JTextField jTextFieldDireccion3;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPiso;
    // End of variables declaration//GEN-END:variables
}
